# Generated by Django 4.1.2 on 2022-10-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpeta1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='email',
            field=models.CharField(default='email', max_length=255),
            preserve_default=False,
        ),
    ]
