# Generated by Django 4.1.2 on 2022-10-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpeta1', '0003_members_adress_members_phone_alter_members_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
